IO_Tester:
  Name: HW Tester
  Version: 1.0.0
  Description: A tool for testing and validating hardware pin configurations.
Debug:
  mode: false
UI:
  UI_Type: Qt
IO_Box:
  Type: MTC_AFT
  AvailableTypes:
  - Demo
  - MTC_FWD
  - MTC_AFT
Timeouts:
  duration: 0.5
  sample_interval: 0.1
  TestStep: 2.5
  Connection: 5.0
  pins_to_stabilize: 0.5
scale:
  voltage: 6.14
  voltage_degredation: 1.5
  voltage_tolerance: 1.5
  zero_voltage_threshold: 0.5
  Analog_voltage_threshold: 13.0
  logic_voltage_threshold: 4.0
Paths:
  Path_1: .
  Path_2: pin_map.json
  reports: C:\temp
  ConnectorAddressMap: connector_Address_map.xlsx
  ConnectorAddressMap_A: connector_Address_A_map.xlsx
  ConnectorAddressMap_B: connector_Address_B_map.xlsx
  ConnectorAddressMap_ControllinoMega: connector_Address_map.xlsx
  ConnectorAddressMap_ArduinoMega: connector_Address_map.xlsx
  ConnectorAddressMap_ArduinoUno: connector_Address_map.xlsx
  powerup_MTC_FWD: tests/DB/MTC_FWD/powerup_MTC_FWD.json
  powerdown_MTC_FWD: tests/DB/MTC_FWD/powerdown_MTC_FWD.json
  powerup_MTC_AFT: tests/DB/MTC_AFT/powerup_MTC_AFT.json
  powerdown_MTC_AFT: tests/DB/MTC_AFT/powerdown_MTC_AFT.json
  database: C:\ArduinoProject\IO_Tester\tests\DB\MK3_Gunner
ExcelColumns:
  ID: H
  Connect: A
  Discrete_Name: B
  Signal_Name: C
  Plug: J
  Pin: K
  Type: D
  Power_Expected: N
  Power_Input: O
  PullUp_Expected: P
  PullUp_Input: Q
  Logic_Pin_Input: R
  Logic_Command: S
  Logic_Expected: T
  Test_Result: U
Measure_value:
  Scale_1: 6
Logging:
  Level: INFO
  File: logs/hwtester.log
Test_trshhold:
  P_T_R_Connection_Tolerance: 0.5
  I_T_R_Connection_Tolerance: 0.5
  L_T_R_Connection_Tolerance: 0.5
